import { createClient } from "@/lib/supabase/server";
import { requireRole } from "@/lib/auth/guard";
import GenerateFeesButton from "./GenerateFeesButton";

function fmt(n) {
  return "Rs. " + Math.round(Number(n) || 0).toLocaleString("en-US");
}
function monthLabel(ym) {
  const [y, m] = ym.split("-").map(Number);
  return new Date(y, m - 1, 1).toLocaleDateString("en-US", { month: "long", year: "numeric" });
}
function dateTimeLabel(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleString("en-US", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
}

export default async function GenerateFeesPage({ searchParams }) {
  // Same three roles as get_or_create_fee_record() itself — this page is a
  // thin wrapper around that function running in a loop, so access matches
  // exactly (see 0021_bulk_fee_generation.sql).
  await requireRole(["Super Admin", "Accountant", "Cashier"]);
  const supabase = createClient();

  const month = searchParams?.month || new Date().toISOString().slice(0, 7);
  const monthDate = `${month}-01`;

  const [{ data, error }, { data: runs }] = await Promise.all([
    supabase.rpc("preview_monthly_fee_generation", { p_month: monthDate }),
    supabase
      .from("fee_generation_runs")
      .select("id, month, started_at, completed_at, total_students, generated_count, skipped_count, failed_count, expected_amount, status, generated_by:users(name)")
      .order("started_at", { ascending: false })
      .limit(20),
  ]);
  const preview = data?.[0] || { active_students: 0, already_generated: 0, to_generate: 0, expected_amount: 0 };

  return (
    <div>
      <h1 className="text-xl font-semibold text-ink">Generate Monthly Fees</h1>
      <p className="text-sm text-slate-500 mt-1">
        Bills every active student for the selected month in one go — Payment Entry only ever
        generates a bill for whichever one student a cashier happens to open, so relying on that
        alone means Expected Fees, Collection %, and Outstanding only reflect however many students
        someone's visited, not the whole academy.
      </p>

      <form className="mt-6 flex flex-wrap items-end gap-3" method="get">
        <div>
          <label className="block text-xs font-medium text-slate-600 mb-1">Month</label>
          <input type="month" name="month" defaultValue={month} className="border border-slate-300 rounded-lg px-3 py-2 text-sm" />
        </div>
        <button className="bg-royal hover:bg-royal-dark text-white text-sm font-medium px-4 py-2 rounded-lg">View</button>
      </form>

      {error ? (
        <p className="text-sm text-brick mt-6">{error.message}</p>
      ) : (
        <div className="bg-white border border-slate-200 rounded-xl p-6 mt-6 max-w-md">
          <div className="text-sm font-semibold text-ink mb-4">{monthLabel(month)}</div>

          <dl className="space-y-3">
            <div className="flex justify-between text-sm">
              <dt className="text-slate-500">Active Students</dt>
              <dd className="font-mono font-medium">{preview.active_students}</dd>
            </div>
            <div className="flex justify-between text-sm">
              <dt className="text-slate-500">Already Generated</dt>
              <dd className="font-mono font-medium">{preview.already_generated}</dd>
            </div>
            <div className="flex justify-between text-sm border-t border-slate-100 pt-3">
              <dt className="text-ink font-medium">To Generate</dt>
              <dd className="font-mono font-semibold text-royal">{preview.to_generate}</dd>
            </div>
            <div className="flex justify-between text-sm">
              <dt className="text-slate-500">Expected Amount</dt>
              <dd className="font-mono font-semibold">{fmt(preview.expected_amount)}</dd>
            </div>
          </dl>

          <div className="mt-6">
            <GenerateFeesButton month={monthDate} toGenerate={preview.to_generate} />
          </div>
        </div>
      )}

      <div className="text-sm font-semibold text-ink mt-8 mb-2">Generation History</div>
      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-slate-500 text-xs uppercase">
            <tr>
              <th className="text-left px-4 py-3">Month</th>
              <th className="text-right px-4 py-3">Generated</th>
              <th className="text-right px-4 py-3">Skipped</th>
              <th className="text-right px-4 py-3">Failed</th>
              <th className="text-right px-4 py-3">Expected</th>
              <th className="text-left px-4 py-3">Generated By</th>
              <th className="text-left px-4 py-3">Generated At</th>
              <th className="text-left px-4 py-3">Status</th>
            </tr>
          </thead>
          <tbody>
            {(runs || []).map((r) => (
              <tr key={r.id} className="border-t border-slate-100">
                <td className="px-4 py-3 font-medium text-ink">{monthLabel(r.month.slice(0, 7))}</td>
                <td className="px-4 py-3 text-right font-mono">{r.generated_count}</td>
                <td className="px-4 py-3 text-right font-mono">{r.skipped_count}</td>
                <td className={`px-4 py-3 text-right font-mono ${r.failed_count > 0 ? "text-brick" : ""}`}>{r.failed_count}</td>
                <td className="px-4 py-3 text-right font-mono">{fmt(r.expected_amount)}</td>
                <td className="px-4 py-3 text-slate-600">{r.generated_by?.name || "—"}</td>
                <td className="px-4 py-3 text-slate-600">{dateTimeLabel(r.started_at)}</td>
                <td className="px-4 py-3">
                  <span className={`text-xs px-2 py-0.5 rounded-full ${
                    r.status === "completed" ? "bg-green-50 text-sage" : r.status === "failed" ? "bg-red-50 text-brick" : "bg-amber-50 text-amber-700"
                  }`}>{r.status}</span>
                </td>
              </tr>
            ))}
            {(!runs || runs.length === 0) && (
              <tr><td colSpan={8} className="px-4 py-10 text-center text-slate-400">No generation runs yet.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
