import { createClient } from "@/lib/supabase/server";
import { requireRole } from "@/lib/auth/guard";
import { getRoleContext } from "@/lib/auth/roles";
import PayrollGenerateForm from "./PayrollGenerateForm";
import PayrollRecordCard from "./PayrollRecordCard";
import ReverseButton from "@/components/ReverseButton";

function fmt(n) {
  return "Rs. " + Math.round(Number(n) || 0).toLocaleString("en-US");
}

function currentMonthStr() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-01`;
}

export default async function PayrollPage({ searchParams }) {
  // "Teacher" belongs here — salary_records' own RLS policy already scopes
  // a Teacher's SELECT to their own row only ("teacher and principal view
  // salary" in 0002_rls.sql), and this is the only page that surfaces the
  // salary slip a Teacher is supposed to be able to see under "Own Salary".
  // Without it, /salary/payroll/[id] (their actual slip) exists but nothing
  // would ever link them to it.
  await requireRole(["Super Admin", "Accountant", "Principal", "Teacher"]);
  const rc = await getRoleContext();
  const canGenerate = rc?.isFinanceStaff || false;
  const canApprove = rc?.canApprove || false;
  const canPay = rc?.isFinanceStaff || false;
  const supabase = createClient();
  const month = searchParams?.month || currentMonthStr();

  const { data: records } = await supabase
    .from("salary_records")
    .select("id, teacher_id, month, base_salary, percentage_total, adjustments_total, gross_salary, paid_total, status, locked, teacher:teachers(name)")
    .eq("month", month)
    .order("created_at");

  const recordIds = (records || []).map((r) => r.id);
  const { data: items } = recordIds.length
    ? await supabase
        .from("salary_items")
        .select("id, salary_record_id, students_count, fee_per_student, collected_amount, percentage, amount, class:classes(name), section:sections(name)")
        .in("salary_record_id", recordIds)
        .eq("item_type", "percentage_share")
    : { data: [] };

  const itemsByRecord = new Map();
  (items || []).forEach((it) => {
    if (!itemsByRecord.has(it.salary_record_id)) itemsByRecord.set(it.salary_record_id, []);
    itemsByRecord.get(it.salary_record_id).push(it);
  });

  const { data: payments } = recordIds.length
    ? await supabase
        .from("salary_payments")
        .select("id, amount, method, paid_on, reversed_at, teacher:teachers(name)")
        .in("salary_record_id", recordIds)
        .order("paid_on", { ascending: false })
    : { data: [] };

  return (
    <div>
      <h1 className="text-xl font-semibold text-ink">{rc?.isTeacher ? "My Salary" : "Monthly Payroll"}</h1>
      <p className="text-sm text-slate-500 mt-1">
        {rc?.isTeacher
          ? "Your salary for each month — calculated from your class percentage shares and any fixed base, never typed in directly."
          : "Generate → Review → Lock → Pay. Percentage shares are calculated from each class's actual fee collections that month — nothing here is typed except the % rule in Salary Configuration."}
      </p>

      {canGenerate && (
        <div className="mt-6">
          <PayrollGenerateForm month={month} />
        </div>
      )}
      {!canGenerate && !rc?.isTeacher && (
        <p className="text-sm text-slate-400 mt-6 mb-2">
          Payroll is generated by Super Admin or Accountant — you can review and approve what's below.
        </p>
      )}

      {(records || []).map((r) => (
        <PayrollRecordCard
          key={r.id}
          record={{ ...r, teacher_name: r.teacher?.name }}
          items={itemsByRecord.get(r.id) || []}
          canApprove={canApprove}
          canPay={canPay}
        />
      ))}

      {(!records || records.length === 0) && (
        <div className="bg-white border border-slate-200 rounded-xl p-8 text-center text-slate-400 text-sm">
          No payroll generated for this month yet. Click "Generate / Refresh Payroll" above.
        </div>
      )}

      {payments && payments.length > 0 && (
        <div className="mt-8">
          <h2 className="text-sm font-semibold text-ink mb-2">Salary Payments — {month}</h2>
          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-slate-50 text-slate-500 text-xs uppercase">
                <tr>
                  <th className="text-left px-4 py-3">Teacher</th>
                  <th className="text-right px-4 py-3">Amount</th>
                  <th className="text-left px-4 py-3">Method</th>
                  <th className="text-left px-4 py-3">Paid On</th>
                  <th className="text-left px-4 py-3"></th>
                </tr>
              </thead>
              <tbody>
                {payments.map((p) => (
                  <tr key={p.id} className={"border-t border-slate-100" + (p.reversed_at ? " opacity-50" : "")}>
                    <td className="px-4 py-3 font-medium text-ink">{p.teacher?.name ?? "—"}</td>
                    <td className="px-4 py-3 text-right font-mono">{fmt(p.amount)}</td>
                    <td className="px-4 py-3 text-slate-600">{p.method}</td>
                    <td className="px-4 py-3 text-slate-600">{p.paid_on}</td>
                    <td className="px-4 py-3">{canGenerate && <ReverseButton table="salary_payments" id={p.id} alreadyReversed={!!p.reversed_at} />}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
